project_id = "oyqrmyuyzurmniifkipt"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://tron-agendamentos.vercel.app"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3000/dashboard/agenda",
  "https://tron-agendamentos.vercel.app",
  "https://tron-agendamentos.vercel.app/dashboard/agenda"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[db]
major_version = 17
